export default interface IHubProps {
    hubLength: number,
    coreRadius: number,
    flange1Radius: number,
    flange1Pos: number,
    flange1Deg: number,
    flange2Radius: number,
    flange2Pos: number,
    flange2Deg: number,
    flange3Radius: number,
    flange3Pos: number,
    flange3Deg: number,
    flange4Radius: number,
    flange4Pos: number,
    flange4Deg: number,
    holeRadius: number,
    holeCount: number,
}
