import type { Metadata } from 'next';
import { ClientProviders } from './providers';
import '@/styles/tailwind-generated.css';
import '@/styles/common.scss';
import '@/styles/colors.scss';
import '@/styles/antd-fix.scss';
import 'antd/dist/reset.css';
import '@/styles/myapp.scss';

export const metadata: Metadata = {
  title: 'my workspace',
  description: 'Generated by create next app',
  icons: { icon: '/favicon.ico' },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh-CN" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
