import '@/src/init';
import Head from 'next/head'
import { Provider, useSelector } from 'react-redux';
import store, { IRootState } from '../src/store';
import dynamic from "next/dynamic";
import Script from 'next/script';
import { useEffect } from 'react';
import { IMessage } from '@stomp/stompjs';

import { ConfigProvider, message } from 'antd';
import { StyleProvider } from '@ant-design/cssinjs';
import { getAlgorithm } from '../src/config/theme';
import zhCN from 'antd/locale/zh_CN';

import { WagmiProvider } from 'wagmi';
import { wagmiConfig } from '@/src/config/wagmi';
import { RabbitMQProvider } from '@/src/components/context/aiNovel';
import mqConfig from '@/src/config/rabbitmq';
import MQHolder from '@/src/components/context/aiNovel/mqHolder';

import AiNovelContextProvider from '@/src/components/context/aiNovel';

import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import TestConsumer from '@/src/components/mq/testConsumer';
import NoticeConsumer from '@/src/components/mq/noticeConsumer';
import mysqlConfig from '@/src/config/mysql';

const queryClient = new QueryClient();
const MyRouter = dynamic(() => import("../src/router"), { ssr: false });

function AppCore() {

    function onMessage(message: IMessage) {
        // console.log(message);
    }

    function onConnectionChange(connected: boolean) {
        console.log(connected);

        if (connected) {
            message.success('已连接后端队列');
        } else {
            message.error('已断开后端队列');
        }
    }

    function onError(error: string) {
        console.log(error);
        message.error('后端队列连接错误: ' + error);
    }

    // 在客户端使用与网站同源的地址
    const getRabbitMQConfig = () => {
        if (typeof window === 'undefined') {
            // SSR 时使用环境变量或默认值
            const host = process.env.RABBITMQ_STOMP_HOST || 'localhost';
            const port = process.env.RABBITMQ_STOMP_PORT || '28010';
            return {
                wsUrl: `http://${host}:${port}/ws`,
                managementUrl: `http://${host}:28008`,
            };
        }
        
        // 客户端：使用与网站同源的地址
        const protocol = window.location.protocol === 'https:' ? 'https:' : 'http:';
        let hostname = window.location.hostname;

        if (process.env.NODE_ENV === 'development') {
            hostname = mysqlConfig.MYSQL_HOST; // 开发环境通过数据库主机地址定位mq地址
        }

        // 根据 docker-compose.yaml，WebSocket 端口映射为 28010:15674
        const wsPort = process.env.NEXT_PUBLIC_RABBITMQ_STOMP_PORT || '28010';
        const mgmtPort = process.env.NEXT_PUBLIC_RABBITMQ_MANAGEMENT_PORT || '28008';
        
        return {
            wsUrl: `${protocol}//${hostname}:${wsPort}/ws`,
            managementUrl: `${protocol}//${hostname}:${mgmtPort}`,
        };
    };

    const rabbitMQConfig = getRabbitMQConfig();

    return (
        <WagmiProvider config={wagmiConfig}>
        <QueryClientProvider client={queryClient}>
        <RabbitMQProvider config={{ 
            ...mqConfig, 
            wsUrl: rabbitMQConfig.wsUrl,
            managementUrl: rabbitMQConfig.managementUrl,
        }}>

            <MyRouter/>

            <MQHolder
                onMessage={onMessage}
                onConnectionChange={onConnectionChange}
                onError={onError}
            >
                {/* <TestConsumer/> */}
                <NoticeConsumer/>
            </MQHolder>

        </RabbitMQProvider>
        </QueryClientProvider>
        </WagmiProvider>
        
    )
}

function AntdApp() {

    const themeConfig = useSelector((state: IRootState) => state.themeSlice.themeConfig);

    // 动态更新 HTML 的 data-theme 属性
    useEffect(() => {
        document.documentElement.setAttribute('data-theme', themeConfig.name);
    }, [themeConfig.name]);

    return (
        <ConfigProvider 
            locale={zhCN}
            theme={{
                algorithm: getAlgorithm(themeConfig.algorithm),
                token: themeConfig.token,
            }}
        >
        <StyleProvider hashPriority="low">
            <AppCore/>
        </StyleProvider>
        </ConfigProvider>

    )
}

export default function Home() {

    return (
        <>
            <Head>
                <title>my workspace</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="f-full-screen">
                <Provider store={store}>
                    <AntdApp/>
                </Provider>
            </main>

            <Script src="/scripts/initGaodeSafeCode.js" strategy='beforeInteractive'/>
            <Script src="https://webapi.amap.com/maps?v=2.0&key=aaf9abee1eb38e393da832ed8d387f4b&plugin=AMap.PlaceSearch,AMap.Driving,AMap.Geocoder" strategy='beforeInteractive'/>
            <script src="https://api.map.baidu.com/api?type=webgl&v=1.0&ak=wODxcvAVzRcq8Y76oqFHvSsmm338mZ19"/>
        
        </>
    )
}
