import '@/src/init';
import Head from 'next/head'
import { Provider } from 'react-redux';
import store from '../src/store';
import zhCN from 'antd/locale/zh_CN';
import { ConfigProvider } from 'antd';
import dynamic from "next/dynamic";

import Script from 'next/script';

const MyRouter = dynamic(() => import("../src/router"), { ssr: false });

export default function Home() {

  return (
    <>
        <Head>
            <title>my workspace</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="f-full-screen">
            <Provider store={store}>
            <ConfigProvider locale={zhCN}>
                <MyRouter/>
            </ConfigProvider>
            </Provider>
        </main>

        <Script src="/scripts/initGaodeSafeCode.js" strategy='beforeInteractive'/>
        <Script src="https://webapi.amap.com/maps?v=2.0&key=aaf9abee1eb38e393da832ed8d387f4b&plugin=AMap.PlaceSearch,AMap.Driving" strategy='beforeInteractive'/>
        <script src="https://api.map.baidu.com/api?type=webgl&v=1.0&ak=wODxcvAVzRcq8Y76oqFHvSsmm338mZ19"/>
      
    </>
  )
}
