import { IWorldState, IWorldStateHistory } from '@/src/types/IAiNoval';

// Mock世界态数据
export const mockWorldStates: IWorldState[] = [
  {
    id: 1,
    worldview_id: 1,
    state_type: 'natural_disaster',
    title: '持续三年的干旱',
    description: '北方地区持续三年干旱，导致粮食减产，引发饥荒',
    status: 'active',
    start_time: 1000000,
    end_time: null,
    duration_days: 1095,
    related_faction_ids: [1, 2],
    related_role_ids: [1, 2],
    related_geo_codes: ['CO001', 'CT001'],
    impact_level: 'high',
    impact_description: '干旱导致粮食危机，多个阵营关系紧张',
    affected_areas: ['economy', 'society'],
    tags: ['天灾', '粮食危机'],
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
  },
  {
    id: 2,
    worldview_id: 1,
    state_type: 'faction_agreement',
    title: '北方联盟与南方联盟的粮食援助协约',
    description: '为应对干旱，北方联盟与南方联盟达成粮食援助协议',
    status: 'active',
    start_time: 1000500,
    end_time: null,
    related_faction_ids: [1, 2],
    related_world_state_ids: [1], // 引用干旱天灾
    impact_level: 'medium',
    affected_areas: ['politics', 'economy'],
    tags: ['协约', '援助'],
    created_at: new Date('2024-01-02'),
    updated_at: new Date('2024-01-02'),
  },
  {
    id: 3,
    worldview_id: 1,
    state_type: 'faction_misunderstanding',
    title: 'A阵营误判B阵营与C阵营的贸易协定为军事同盟',
    description: 'A阵营错误地认为B阵营与C阵营的贸易协定是军事同盟，导致关系紧张',
    status: 'active',
    start_time: 1001000,
    related_faction_ids: [1, 2, 3],
    related_world_state_ids: [2], // 引用协约
    impact_level: 'high',
    affected_areas: ['politics', 'military'],
    tags: ['误判', '关系紧张'],
    created_at: new Date('2024-01-03'),
    updated_at: new Date('2024-01-03'),
  },
  {
    id: 4,
    worldview_id: 1,
    state_type: 'character_agreement',
    title: '角色A与角色B的秘密协议',
    description: '角色A与角色B达成秘密协议，共同对抗某个威胁',
    status: 'active',
    start_time: 1001500,
    related_role_ids: [1, 2],
    impact_level: 'medium',
    affected_areas: ['politics'],
    tags: ['秘密协议'],
    created_at: new Date('2024-01-04'),
    updated_at: new Date('2024-01-04'),
  },
  {
    id: 5,
    worldview_id: 1,
    state_type: 'character_perception_gap',
    title: '角色A认为角色B只有1000兵力，但实际有5000',
    description: '角色A对角色B的军事实力存在严重误判',
    status: 'active',
    start_time: 1002000,
    related_role_ids: [1, 2],
    related_world_state_ids: [4], // 引用人物协议
    impact_level: 'high',
    affected_areas: ['military'],
    tags: ['信息差', '军事误判'],
    created_at: new Date('2024-01-05'),
    updated_at: new Date('2024-01-05'),
  },
];

// Mock状态历史数据
export const mockWorldStateHistories: IWorldStateHistory[] = [
  {
    id: 1,
    world_state_id: 1,
    old_status: undefined,
    new_status: 'active',
    change_reason: '创建',
    changed_at: new Date('2024-01-01'),
  },
];
