services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: nsds123456
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    name: mysql_data
